drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    //by default as identity:자동으로 값채워주기 위해 사용
    name varchar(255),
    primary key (id)
    );